---
title: "git_00"
author: "Robert Solis"
date: "Year 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Girt with a boyish garb for boyish task,  
Eager she wields her spade: yet loves as well  
Rest on a friendly knee, intent to ask  
The tale he loves to tell.  
Rude spirits of the seething outer strife  
  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
He halted in the wind, and -- what was that  
Far in the maples, pale, but not a ghost?  
He stood there bringing March against his thought,  
And yet too ready to believe the most.  
  
"Oh, that's the Paradise-in-bloom," I said;  
  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
But, because they had stars, all the Star-Belly Sneetches  
Would brag, “We’re the best kind of Sneetch on the beaches.”  
With their snoots in the air, they would sniff and they’d snort  
“We’ll have nothing to do with the Plain-Belly sort!”  
And whenever they met some, when they were out walking,  
They’d hike right on past them without even talking.  
  
When the Star-Belly children went out to play ball,  
Could a Plain Belly get in the game…? Not at all.  
You only could play if your bellies had stars  
And the Plain-Belly children had none upon thars.  
  
When the Star-Belly Sneetches had frankfurter roasts  
Or picnics or parties or marshmallow toasts,  
They never invited the Plain-Belly Sneetches.  
They left them out cold, in the dark of the beaches.  
They kept them away. Never let them come near.  
And that’s how they treated them year after year.  
  
  